"""ffmpeg stitching command builder for DJI Osmo 360 .OSV files.

Two modes:

- ``v360`` (validated baseline): ``hstack`` of the two fisheyes then a ``v360``
  filter (input=dfisheye, ih_fov=iv_fov=190, yaw=90). lanczos/bilinear
  interpolation, 10-bit chain preserved for HEVC.
- ``calibrated``: each fisheye is reprojected by the ``remap`` filter with the
  maps from the factory calibration (see maps.py), then the two
  equirectangular images are blended by ``maskedmerge`` with a gradient mask
  (±5° around the seams). Known limits, measured during validation
  (see work/engine/):
    * ``remap`` samples nearest neighbor (no interpolation): very
      slight sharpness loss vs v360 lanczos, especially at low resolutions;
    * 8-bit chain (gbrp) because remap+maskedmerge are most robust there;
    * in return, the per-lens geometry (optical centers, real
      distortion, extrinsics) and the ±5° blend remove the visible step at the
      baseline seams (smooth blending, continuity of crossing objects).
  The residual parallax on very close objects (<0.5 m) remains visible in
  both modes (the lens pupils are not merged).

Audio is copied as is. ``-progress pipe:1 -nostats`` is always added
for tracking by jobs.py.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass

try:  # package import (app.core.stitch) or flat import (tests/tooling)
    from .maps import MapSet
except ImportError:  # pragma: no cover
    from maps import MapSet  # type: ignore

_HAS_NVENC: bool | None = None


@dataclass
class StitchOptions:
    out_w: int = 7680            # 7680, 6144 or 3840 (h = w/2)
    codec: str = "hevc"          # "hevc" | "h264"
    encoder: str = "auto"        # "auto"->nvenc if available, otherwise cpu; "nvenc" | "cpu"
    quality: int = 20            # cq nvenc / crf cpu
    interp: str = "lanczos"      # "lanczos" | "line" (v360 mode only)
    mode: str = "auto"           # "auto" | "v360" | "calibrated"
    fps_out: float | None = None # None = keep; e.g. 5 for Street View
    stabilize: bool = False           # gyroscopic stabilization (phase 2)
    stabilize_mode: str = "horizon"   # "horizon" | "lock" | "smooth"
    stabilize_strength: float = 1.0   # normalized strength in [0.0, 1.0]


def has_nvenc() -> bool:
    """True if ffmpeg exposes hevc_nvenc/h264_nvenc (result cached)."""
    global _HAS_NVENC
    if _HAS_NVENC is None:
        _HAS_NVENC = False
        if shutil.which("ffmpeg"):
            try:
                out = subprocess.run(
                    ["ffmpeg", "-hide_banner", "-encoders"],
                    capture_output=True, text=True, timeout=20).stdout
                _HAS_NVENC = "hevc_nvenc" in out or "h264_nvenc" in out
            except (OSError, subprocess.SubprocessError):
                pass
    return _HAS_NVENC


def _resolve_mode(opts: StitchOptions, maps: MapSet | None) -> str:
    if opts.mode in ("v360", "calibrated"):
        return opts.mode
    # auto: calibrated if maps from a real calibration are available.
    if maps is not None and maps.calibrated:
        return "calibrated"
    return "v360"


def _encoder_args(opts: StitchOptions) -> tuple[list[str], str]:
    """Returns (video codec args, filter output pix_fmt)."""
    enc = opts.encoder
    if enc == "auto":
        enc = "nvenc" if has_nvenc() else "cpu"
    q = str(int(opts.quality))
    if opts.codec == "h264":
        pix = "yuv420p"
        if enc == "nvenc":
            args = ["-c:v", "h264_nvenc", "-rc", "vbr", "-cq", q, "-b:v", "0",
                    "-preset", "p5"]
        else:
            args = ["-c:v", "libx264", "-crf", q, "-preset", "medium"]
    else:  # hevc
        pix = "yuv420p10le"
        if enc == "nvenc":
            args = ["-c:v", "hevc_nvenc", "-rc", "vbr", "-cq", q, "-b:v", "0",
                    "-preset", "p5", "-tag:v", "hvc1"]
        else:
            args = ["-c:v", "libx265", "-crf", q, "-preset", "medium",
                    "-tag:v", "hvc1"]
    return args, pix


def build_command(input_path: str, output_path: str, opts: StitchOptions,
                  maps: MapSet | None = None,
                  stabilize_cmd: str | None = None) -> list[str]:
    """Builds the complete ffmpeg command (argument list).

    ``stabilize_cmd``: path to a ``sendcmd`` command file (generated by
    ``stabilize.build_sendcmd``) driving the per-frame yaw/pitch/roll rotation.
    Generated by jobs.py when ``opts.stabilize`` is active and the IMU is
    present. Injection:
      * v360 mode: the stitch's v360 (only v360 in the graph) is initialized at
        NEUTRAL rotation (yaw=0:pitch=0:roll=0) — essential because v360 commands
        COMPOSE with the init orientation — and driven by ``sendcmd``.
        The supplied angles already include the baseline yaw=90 alignment.
      * calibrated mode: the remap stitch contains no v360; we add a
        dedicated (unique) v360=e:e, neutral init, driven by ``sendcmd``.
    Without ``stabilize_cmd`` the behavior is strictly unchanged (baseline).
    """
    mode = _resolve_mode(opts, maps)
    if mode == "calibrated" and maps is None:
        raise ValueError("mode 'calibrated' requested without MapSet")
    out_w = int(opts.out_w)
    out_h = out_w // 2
    if maps is not None and mode == "calibrated" and (
            maps.out_w != out_w or maps.out_h != out_h):
        raise ValueError(
            f"MapSet {maps.out_w}x{maps.out_h} != output {out_w}x{out_h}")

    interp = opts.interp if opts.interp in ("lanczos", "line") else "lanczos"
    fps = f"fps={opts.fps_out:g}," if opts.fps_out else ""
    enc_args, pix = _encoder_args(opts)
    stab = bool(stabilize_cmd)
    # escape any comma/semicolon in the path for filter_complex
    sc = _escape_filter_path(stabilize_cmd) if stab else ""

    cmd = ["ffmpeg", "-hide_banner", "-y", "-i", input_path]

    if mode == "v360":
        if stab:
            # only v360 in the graph: NEUTRAL init + sendcmd (angles pre-folded
            # with the baseline yaw=90). 10-bit chain preserved.
            graph = (
                f"[0:0][0:1]hstack[s];"
                f"[s]{fps}sendcmd=f={sc},"
                f"v360=input=dfisheye:output=e:ih_fov=190:iv_fov=190:"
                f"yaw=0:pitch=0:roll=0:w={out_w}:h={out_h}:interp={interp},"
                f"format={pix}[v]"
            )
        else:
            # validated baseline: yaw=90, 10-bit chain preserved.
            graph = (
                f"[0:0][0:1]hstack[s];"
                f"[s]{fps}v360=input=dfisheye:output=e:ih_fov=190:iv_fov=190:"
                f"yaw=90:w={out_w}:h={out_h}:interp={interp},format={pix}[v]"
            )
    else:
        for i in range(2):
            cmd += ["-i", maps.xmaps[i], "-i", maps.ymaps[i]]
        cmd += ["-i", maps.blend_mask]
        # inputs: 1=xmap0 2=ymap0 3=xmap1 4=ymap1 5=mask
        graph = (
            f"[0:0]{fps}format=gbrp[b0];"
            f"[b0][1:v][2:v]remap=fill=black[e0];"
            f"[0:1]{fps}format=gbrp[b1];"
            f"[b1][3:v][4:v]remap=fill=black[e1];"
            f"[5:v]format=gbrp[mk];"
            f"[e0][e1][mk]maskedmerge[mg];"
        )
        if stab:
            # dedicated v360=e:e (only v360), neutral init, driven by sendcmd.
            graph += (
                f"[mg]sendcmd=f={sc},v360=e:e:yaw=0:pitch=0:roll=0:"
                f"w={out_w}:h={out_h}:interp={interp},format={pix}[v]"
            )
        else:
            graph += f"[mg]format={pix}[v]"

    cmd += ["-filter_complex", graph, "-map", "[v]", "-map", "0:a?",
            "-c:a", "copy"]
    cmd += enc_args
    cmd += ["-progress", "pipe:1", "-nostats", output_path]
    return cmd


def _escape_filter_path(path: str) -> str:
    """Escapes a path for a filter's ``f=`` option in -filter_complex
    (the characters ``\\ : , ; ' [ ]`` are special there)."""
    out = []
    for ch in path:
        if ch in "\\:,;'[]":
            out.append("\\" + ch)
        else:
            out.append(ch)
    return "".join(out)
